server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: ADD-TO-CART-SERVICE
          uri: lb://ADD-TO-CART-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: ADD-TO-FAVOURITE-SERVICE
          uri: lb://ADD-TO-FAVOURITE-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: BANNER-SERVICE
          uri: lb://BANNER-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: CHECKOUT-SERVICE
          uri: lb://CHECKOUT-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: LANGUAGE-SERVICE
          uri: lb://LANGUAGE-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: NEWSLETTER-SERVICE
          uri: lb://NEWSLETTER-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: ORDER-RETURN-SERVICE
          uri: lb://ORDER-RETURN-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: SUB-CATEGORY-SERVICE
          uri: lb://SUB-CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/elastic/**

        - id: DISCOVERY-SERVICE
          uri: http://localhost:8761/
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
